all:
  hosts:
  children:
    servers:
      hosts:
        10.0.5.5:
          hostname: dc-blue1
        10.0.5.6:
          hostname: fs01
          lan_ip: 10.0.5.6
      vars:
        domain_ou_path: 'OU=servers,OU=computers,OU=blue1,DC=blue1,DC=local'
        account_ou: 'OU=Accounts,OU=blue1,DC=blue1,DC=local'

    
    workstations:
      hosts:
        10.0.5.86:
          hostname: wks1
        10.0.5.87:
          hostname: wks2
      vars:
        domain_ou_path: 'OU=workstations,OU=computers,OU=blue1,DC=blue1,DC=local'
  vars:
    ansible_user: deployer
    device: Ethernet0
    netmask: 255.255.255.0
    gateway: 10.0.5.2
    name_server: 10.0.5.5
    domain: blue1.local
    ansible_shell_type: powershell
    base_dc: blue1